/**:
  ros__parameters:
    joints_map:
      left_front:
        - l_f_joint
        - l_f_1link
        - l_f_2link

      right_front:
        - r_f_joint
        - r_f_1link
        - r_f_2link

      left_hind:
        - l_b_joint
        - l_b_1link
        - l_b_2link

      right_hind:
        - r_b_joint
        - r_b_1link
        - r_b_2link
